all:
  .general:
    # Sample related constants
    sample_pictures_dir:  /sample_pictures
    temperature_unit:     ÂºC
    conductivity_unit:    S/m
    salinity_unit:        ppm
    altitude_unit:        m
    
    # Location related constants
    location_pictures_dir:  /location_pictures
    max_location_pictures:  5
    
    # Pictures and thumbnails management constants
    pictures_dir:           /uploads
    thumbnails_dir:         /thumbnails
    max_picture_size:       512000
    max_thumbnail_size:     75
    
    # Common constants
    max_list_items:             15
    no_data_message:            no data
    default_sort_direction:     asc
    search_box_hint:            Search...
    gps_coordinates_separator:  ','
    
    # Google Maps API management constants
    map_pictures_dir:   /images/maps
    default_latitude:   27.991232
    default_longitude:  -15.368787
    
  sf_guard_plugin:
    routes_register:        true
    allow_login_with_email: false
    success_signout_url:    /login
  google:
    maps_api_keys:
      bna.es:                              ABQIAAAAnfs7bKE82qgb3Zc2YyS-oBT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3VcA
      greenhouse.marinebiotechnology.org:  ABQIAAAA7TbcaKTnh_hjjGDvnknQPhSthKBdDxmLzOzI0fHMyeiqcd14nBQ4PGf_DYgy4M__dXQzKYkA3MDFEQ
